import { SickLeaveCase, Task, TimelineEvent, Document } from '@/types/sickLeave';

export const mockSickLeaveCases: SickLeaveCase[] = [
  {
    id: 'case-1',
    employee_id: 'emp-1',
    start_date: '2025-11-10',
    end_date: null,
    functional_limitations: 'Kan niet langdurig staan of zitten door koorts en vermoeidheid',
    case_status: 'actief',
    created_by: 'mock-hr-user-id',
    created_at: '2025-11-10T08:30:00Z',
    updated_at: '2025-11-10T08:30:00Z',
    employee: {
      voornaam: 'Jan',
      achternaam: 'Jansen',
      email: 'jan.jansen@example.com',
    },
  },
  {
    id: 'case-2',
    employee_id: 'emp-2',
    start_date: '2025-11-05',
    end_date: null,
    functional_limitations: 'Kan niet langer dan 2 uur achter elkaar zitten, geen zware til- of bukbewegingen',
    case_status: 'herstel_gemeld',
    created_by: 'mock-hr-user-id',
    created_at: '2025-11-05T09:15:00Z',
    updated_at: '2025-11-12T14:20:00Z',
    employee: {
      voornaam: 'Sarah',
      achternaam: 'de Vries',
      email: 'sarah.devries@example.com',
    },
  },
  {
    id: 'case-3',
    employee_id: 'emp-3',
    start_date: '2025-10-20',
    end_date: '2025-11-01',
    functional_limitations: 'Beperkte mobiliteit na operatie, geen langdurig lopen of staan',
    case_status: 'gesloten',
    created_by: 'mock-hr-user-id',
    created_at: '2025-10-20T10:00:00Z',
    updated_at: '2025-11-01T16:00:00Z',
    employee: {
      voornaam: 'Mohamed',
      achternaam: 'Ali',
      email: 'mohamed.ali@example.com',
    },
  },
  {
    id: 'case-4',
    employee_id: 'emp-4',
    start_date: '2025-11-12',
    end_date: null,
    functional_limitations: 'Concentratieproblemen, vermoeidheid, niet in staat om normale werkdruk aan te kunnen',
    case_status: 'actief',
    created_by: 'mock-hr-user-id',
    created_at: '2025-11-12T11:45:00Z',
    updated_at: '2025-11-12T11:45:00Z',
    employee: {
      voornaam: 'Lisa',
      achternaam: 'Vermeulen',
      email: 'lisa.vermeulen@example.com',
    },
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    case_id: 'case-1',
    title: 'Eerste contact medewerker',
    description: 'Neem binnen 24 uur contact op met de medewerker',
    deadline: '2025-11-11',
    task_status: 'completed',
    assigned_to: 'mock-user-id-123',
    created_at: '2025-11-10T08:30:00Z',
    completed_at: '2025-11-10T14:00:00Z',
    completed_by: 'mock-user-id-123',
    updated_at: '2025-11-10T14:00:00Z',
    gespreksonderwerpen: null,
    toegestane_vragen: null,
    verboden_vragen: null,
    juridische_context: null,
    notes: null,
  },
  {
    id: 'task-2',
    case_id: 'case-1',
    title: 'Plan gesprek met manager',
    description: 'Informeer de manager en plan voortgangsgesprek',
    deadline: '2025-11-15',
    task_status: 'open',
    assigned_to: 'mock-user-id-123',
    created_at: '2025-11-10T08:30:00Z',
    completed_at: null,
    completed_by: null,
    updated_at: '2025-11-10T08:30:00Z',
    gespreksonderwerpen: null,
    toegestane_vragen: null,
    verboden_vragen: null,
    juridische_context: null,
    notes: null,
  },
  {
    id: 'task-3',
    case_id: 'case-2',
    title: 'Re-integratie plan opstellen',
    description: 'Maak samen met medewerker een re-integratie plan',
    deadline: '2025-11-18',
    task_status: 'in_progress',
    assigned_to: 'mock-user-id-123',
    created_at: '2025-11-05T09:15:00Z',
    completed_at: null,
    completed_by: null,
    updated_at: '2025-11-12T10:00:00Z',
    gespreksonderwerpen: null,
    toegestane_vragen: null,
    verboden_vragen: null,
    juridische_context: null,
    notes: null,
  },
  {
    id: 'task-4',
    case_id: 'case-4',
    title: 'Bedrijfsarts raadplegen',
    description: 'Maak afspraak met bedrijfsarts binnen 6 weken',
    deadline: '2025-12-24',
    task_status: 'open',
    assigned_to: 'mock-user-id-123',
    created_at: '2025-11-12T11:45:00Z',
    completed_at: null,
    completed_by: null,
    updated_at: '2025-11-12T11:45:00Z',
    gespreksonderwerpen: null,
    toegestane_vragen: null,
    verboden_vragen: null,
    juridische_context: null,
    notes: null,
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'event-1',
    case_id: 'case-1',
    event_type: 'ziekmelding',
    description: 'Ziekmelding ontvangen: Griep en koorts',
    created_by: 'emp-1',
    created_at: '2025-11-10T08:30:00Z',
    date: '2025-11-10',
    metadata: null,
    creator: {
      voornaam: 'Jan',
      achternaam: 'Jansen',
    },
  },
  {
    id: 'event-2',
    case_id: 'case-1',
    event_type: 'notitie',
    description: 'Telefonisch contact gehad. Medewerker heeft hoge koorts.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-10T14:00:00Z',
    date: '2025-11-10',
    metadata: null,
    creator: {
      voornaam: 'HR',
      achternaam: 'Specialist',
    },
  },
  {
    id: 'event-3',
    case_id: 'case-2',
    event_type: 'ziekmelding',
    description: 'Ziekmelding ontvangen: Rugklachten',
    created_by: 'emp-2',
    created_at: '2025-11-05T09:15:00Z',
    date: '2025-11-05',
    metadata: null,
    creator: {
      voornaam: 'Sarah',
      achternaam: 'de Vries',
    },
  },
  {
    id: 'event-4',
    case_id: 'case-2',
    event_type: 'gesprek',
    description: 'Voortgangsgesprek gehad. Fysiotherapie helpt goed.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-12T14:20:00Z',
    date: '2025-11-12',
    metadata: null,
    creator: {
      voornaam: 'HR',
      achternaam: 'Specialist',
    },
  },
  {
    id: 'event-5',
    case_id: 'case-2',
    event_type: 'herstel',
    description: 'Status gewijzigd naar herstel gemeld. Re-integratie start volgende week.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-12T14:25:00Z',
    date: '2025-11-12',
    metadata: null,
    creator: {
      voornaam: 'HR',
      achternaam: 'Specialist',
    },
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    case_id: 'case-1',
    file_name: 'Medische verklaring.pdf',
    document_type: 'medisch_attest',
    file_url: '/placeholder.svg',
    uploaded_by: 'mock-hr-user-id',
    created_at: '2025-11-10T09:00:00Z',
  },
  {
    id: 'doc-2',
    case_id: 'case-1',
    file_name: 'Re-integratie plan.docx',
    document_type: 'plan_van_aanpak',
    file_url: '/placeholder.svg',
    uploaded_by: 'mock-hr-user-id',
    created_at: '2025-11-11T11:30:00Z',
  },
];