import { SickLeaveCase, Task, TimelineEvent, Document } from '@/types/sickLeave';

export const mockSickLeaveCases: SickLeaveCase[] = [
  {
    id: 'case-1',
    medewerker_id: 'emp-1',
    medewerker_naam: 'Jan Jansen',
    start_datum: '2025-11-10',
    eind_datum: null,
    reden: 'Griep en koorts',
    status: 'actief',
    manager_id: 'mgr-1',
    notities: 'Telefonisch contact gehad. Verwacht volgende week beterschap.',
    created_at: '2025-11-10T08:30:00Z',
    updated_at: '2025-11-10T08:30:00Z',
  },
  {
    id: 'case-2',
    medewerker_id: 'emp-2',
    medewerker_naam: 'Sarah de Vries',
    start_datum: '2025-11-05',
    eind_datum: null,
    reden: 'Rugklachten',
    status: 'herstel',
    manager_id: 'mgr-1',
    notities: 'Fysiotherapie gestart. Geleidelijke werkhervatting gepland.',
    created_at: '2025-11-05T09:15:00Z',
    updated_at: '2025-11-12T14:20:00Z',
  },
  {
    id: 'case-3',
    medewerker_id: 'emp-3',
    medewerker_naam: 'Mohamed Ali',
    start_datum: '2025-10-20',
    eind_datum: '2025-11-01',
    reden: 'Operatie knie',
    status: 'afgesloten',
    manager_id: 'mgr-2',
    notities: 'Volledig hersteld. Werkzaamheden hervat op 1 november.',
    created_at: '2025-10-20T10:00:00Z',
    updated_at: '2025-11-01T16:00:00Z',
  },
  {
    id: 'case-4',
    medewerker_id: 'emp-4',
    medewerker_naam: 'Lisa Vermeulen',
    start_datum: '2025-11-12',
    eind_datum: null,
    reden: 'Burn-out klachten',
    status: 'actief',
    manager_id: 'mgr-1',
    notities: 'Bedrijfsarts geraadpleegd. Re-integratie traject opgestart.',
    created_at: '2025-11-12T11:45:00Z',
    updated_at: '2025-11-12T11:45:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    case_id: 'case-1',
    titel: 'Eerste contact medewerker',
    beschrijving: 'Neem binnen 24 uur contact op met de medewerker',
    deadline: '2025-11-11',
    status: 'completed',
    toegewezen_aan: 'mock-user-id-123',
    created_at: '2025-11-10T08:30:00Z',
    completed_at: '2025-11-10T14:00:00Z',
  },
  {
    id: 'task-2',
    case_id: 'case-1',
    titel: 'Plan gesprek met manager',
    beschrijving: 'Informeer de manager en plan voortgangsgesprek',
    deadline: '2025-11-15',
    status: 'open',
    toegewezen_aan: 'mock-user-id-123',
    created_at: '2025-11-10T08:30:00Z',
    completed_at: null,
  },
  {
    id: 'task-3',
    case_id: 'case-2',
    titel: 'Re-integratie plan opstellen',
    beschrijving: 'Maak samen met medewerker een re-integratie plan',
    deadline: '2025-11-18',
    status: 'in_progress',
    toegewezen_aan: 'mock-user-id-123',
    created_at: '2025-11-05T09:15:00Z',
    completed_at: null,
  },
  {
    id: 'task-4',
    case_id: 'case-4',
    titel: 'Bedrijfsarts raadplegen',
    beschrijving: 'Maak afspraak met bedrijfsarts binnen 6 weken',
    deadline: '2025-12-24',
    status: 'open',
    toegewezen_aan: 'mock-user-id-123',
    created_at: '2025-11-12T11:45:00Z',
    completed_at: null,
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'event-1',
    case_id: 'case-1',
    event_type: 'ziekmelding',
    beschrijving: 'Ziekmelding ontvangen: Griep en koorts',
    created_by: 'emp-1',
    created_at: '2025-11-10T08:30:00Z',
  },
  {
    id: 'event-2',
    case_id: 'case-1',
    event_type: 'notitie',
    beschrijving: 'Telefonisch contact gehad. Medewerker heeft hoge koorts.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-10T14:00:00Z',
  },
  {
    id: 'event-3',
    case_id: 'case-2',
    event_type: 'ziekmelding',
    beschrijving: 'Ziekmelding ontvangen: Rugklachten',
    created_by: 'emp-2',
    created_at: '2025-11-05T09:15:00Z',
  },
  {
    id: 'event-4',
    case_id: 'case-2',
    event_type: 'gesprek',
    beschrijving: 'Voortgangsgesprek gehad. Fysiotherapie helpt goed.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-12T14:20:00Z',
  },
  {
    id: 'event-5',
    case_id: 'case-2',
    event_type: 'herstel',
    beschrijving: 'Status gewijzigd naar herstel. Re-integratie start volgende week.',
    created_by: 'mock-user-id-123',
    created_at: '2025-11-12T14:25:00Z',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    case_id: 'case-1',
    naam: 'Medische verklaring.pdf',
    categorie: 'medisch',
    bestand_url: '/placeholder.svg',
    bestand_type: 'application/pdf',
    grootte: 245000,
    uploaded_by: 'HR Specialist',
    created_at: '2025-11-10T09:00:00Z',
  },
  {
    id: 'doc-2',
    case_id: 'case-1',
    naam: 'Re-integratie plan.docx',
    categorie: 're-integratie',
    bestand_url: '/placeholder.svg',
    bestand_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    grootte: 156000,
    uploaded_by: 'HR Specialist',
    created_at: '2025-11-11T11:30:00Z',
  },
];
