-- Email drafts table for automation workflows
-- This table stores email drafts generated by n8n workflows for review before sending

-- Email drafts table
CREATE TABLE IF NOT EXISTS email_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Email content
  to_email TEXT NOT NULL,
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  
  -- Metadata
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'failed', 'cancelled')),
  type TEXT NOT NULL, -- 'quote_expiration', 'stale_lead', 'onboarding', etc
  
  -- Foreign keys
  quote_id UUID REFERENCES quotes(id) ON DELETE SET NULL,
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  
  -- Automation tracking
  created_by_automation BOOLEAN DEFAULT TRUE,
  workflow_id TEXT, -- n8n workflow that created it
  
  -- Send tracking
  sent_at TIMESTAMPTZ,
  sent_by UUID REFERENCES profiles(id),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_email_drafts_status ON email_drafts(status) WHERE status = 'draft';
CREATE INDEX idx_email_drafts_project ON email_drafts(project_id);
CREATE INDEX idx_email_drafts_created ON email_drafts(created_at DESC);

-- RLS Policies
ALTER TABLE email_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view email drafts"
  ON email_drafts FOR SELECT
  USING (
    public.user_role() IN ('super_admin', 'ADMIN', 'MANAGER', 'SALES', 'SUPPORT')
  );

CREATE POLICY "Users can update email drafts"
  ON email_drafts FOR UPDATE
  USING (
    public.user_role() IN ('super_admin', 'ADMIN', 'MANAGER', 'SALES')
  );

CREATE POLICY "Users can insert email drafts"
  ON email_drafts FOR INSERT
  WITH CHECK (
    public.user_role() IN ('super_admin', 'ADMIN', 'MANAGER', 'SALES')
  );

CREATE POLICY "Service role can insert email drafts"
  ON email_drafts FOR INSERT
  WITH CHECK (
    auth.jwt()->>'role' = 'service_role'
  );

-- Trigger for updated_at
CREATE TRIGGER update_email_drafts_updated_at
  BEFORE UPDATE ON email_drafts
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE email_drafts IS 'Email drafts generated by n8n workflows for review before sending';
COMMENT ON COLUMN email_drafts.type IS 'Workflow type: quote_expiration, stale_lead, onboarding, drip_campaign, etc';
