import { useMutation } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Calendar, 
  Clock, 
  MapPin, 
  Video, 
  Trash2,
  ExternalLink,
  FileText
} from 'lucide-react';
import { format } from 'date-fns';
import { nl } from 'date-fns/locale';
import { toast } from 'sonner';

interface CalendarEvent {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  event_type: string;
  start_time: string;
  end_time: string;
  all_day: boolean;
  color: string;
  location: string | null;
  is_virtual: boolean;
  meeting_url: string | null;
  leave_request_id: string | null;
  task_id: string | null;
}

interface EventDetailDialogProps {
  event: CalendarEvent;
  open: boolean;
  onClose: () => void;
  onDeleted: () => void;
}

const eventTypeLabels: Record<string, string> = {
  meeting: 'Meeting',
  task: 'Taak',
  leave: 'Verlof',
  birthday: 'Verjaardag',
  training: 'Training',
  review: 'Review',
  deadline: 'Deadline',
  other: 'Overig'
};

export function EventDetailDialog({ event, open, onClose, onDeleted }: EventDetailDialogProps) {
  const isAutoGenerated = !!(event.leave_request_id || event.task_id);
  
  const deleteEvent = useMutation({
    mutationFn: async () => {
      const { error } = await supabase
        .from('calendar_events')
        .delete()
        .eq('id', event.id);

      if (error) throw error;
    },
    onSuccess: () => {
      onDeleted();
    },
    onError: (error: any) => {
      console.error('Error deleting event:', error);
      toast.error('Fout bij verwijderen event: ' + error.message);
    }
  });

  const handleDelete = () => {
    if (isAutoGenerated) {
      toast.error('Automatisch gegenereerde events kunnen niet worden verwijderd');
      return;
    }
    
    if (confirm('Weet je zeker dat je dit event wilt verwijderen?')) {
      deleteEvent.mutate();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <DialogTitle className="text-xl">{event.title}</DialogTitle>
              <div className="flex items-center gap-2 mt-2">
                <Badge 
                  style={{ 
                    backgroundColor: event.color,
                    color: 'white'
                  }}
                >
                  {eventTypeLabels[event.event_type] || event.event_type}
                </Badge>
                {isAutoGenerated && (
                  <Badge variant="outline">
                    Auto-gegenereerd
                  </Badge>
                )}
              </div>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4">
          {/* Date/Time */}
          <div className="flex items-start gap-3">
            <Calendar className="h-5 w-5 text-muted-foreground mt-0.5" />
            <div>
              <div className="font-medium">
                {format(new Date(event.start_time), 'EEEE d MMMM yyyy', { locale: nl })}
              </div>
              {!event.all_day && (
                <div className="text-sm text-muted-foreground flex items-center gap-1 mt-1">
                  <Clock className="h-4 w-4" />
                  {format(new Date(event.start_time), 'HH:mm')} - {format(new Date(event.end_time), 'HH:mm')}
                </div>
              )}
              {event.all_day && (
                <div className="text-sm text-muted-foreground">
                  Hele dag
                </div>
              )}
            </div>
          </div>

          {/* Description */}
          {event.description && (
            <div className="flex items-start gap-3">
              <FileText className="h-5 w-5 text-muted-foreground mt-0.5" />
              <div className="flex-1">
                <div className="text-sm text-muted-foreground whitespace-pre-wrap">
                  {event.description}
                </div>
              </div>
            </div>
          )}

          {/* Location */}
          {event.location && (
            <div className="flex items-start gap-3">
              <MapPin className="h-5 w-5 text-muted-foreground mt-0.5" />
              <div>
                <div className="text-sm">{event.location}</div>
              </div>
            </div>
          )}

          {/* Meeting URL */}
          {event.is_virtual && event.meeting_url && (
            <div className="flex items-start gap-3">
              <Video className="h-5 w-5 text-muted-foreground mt-0.5" />
              <div className="flex-1">
                <a
                  href={event.meeting_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-primary hover:underline flex items-center gap-1"
                >
                  Deelnemen aan meeting
                  <ExternalLink className="h-3 w-3" />
                </a>
              </div>
            </div>
          )}

          {/* Auto-generated notice */}
          {isAutoGenerated && (
            <div className="bg-muted p-3 rounded-lg text-sm text-muted-foreground">
              {event.leave_request_id && 'Dit event is automatisch aangemaakt vanuit een goedgekeurde verlofaanvraag.'}
              {event.task_id && 'Dit event is automatisch aangemaakt vanuit een taak met deadline.'}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={onClose}
          >
            Sluiten
          </Button>
          {!isAutoGenerated && (
            <Button
              variant="destructive"
              onClick={handleDelete}
              disabled={deleteEvent.isPending}
            >
              <Trash2 className="h-4 w-4 mr-2" />
              {deleteEvent.isPending ? 'Verwijderen...' : 'Verwijderen'}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
